-- MySQL Script generated by MySQL Workbench
-- Mon Apr  7 11:34:25 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Projet_karting
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Projet_karting` ;

-- -----------------------------------------------------
-- Schema Projet_karting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Projet_karting` DEFAULT CHARACTER SET utf8 ;
USE `Projet_karting` ;

-- -----------------------------------------------------
-- Table `Projet_karting`.`Karts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Karts`;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Karts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `number_UNIQUE` (`number` ASC) VISIBLE) 
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Projet_karting`.`Pilots`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Pilots` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Pilots` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Firstname` VARCHAR(45) NULL,
  `Lastname` VARCHAR(45) NULL,
  `Pseudo` VARCHAR(255) NOT NULL,
  `Date_of_birth` DATETIME NULL,
  `Pw_hash` VARCHAR(255) NULL, 
  `level` INT DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_karting`.`Pilots_has_Karts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Pilots_has_Karts` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Pilots_has_Karts` (
  `Pilots_id` INT NOT NULL,
  `Karts_id` INT NOT NULL,
  `start_date` DATETIME NULL,
  `end_date` DATETIME NULL,
  PRIMARY KEY (`Pilots_id`, `Karts_id`),
  INDEX `fk_Pilots_has_Karts_Karts1_idx` (`Karts_id` ASC) VISIBLE,
  INDEX `fk_Pilots_has_Karts_Pilots_idx` (`Pilots_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pilots_has_Karts_Pilots`
    FOREIGN KEY (`Pilots_id`)
    REFERENCES `Projet_karting`.`Pilots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pilots_has_Karts_Karts1`
    FOREIGN KEY (`Karts_id`)
    REFERENCES `Projet_karting`.`Karts` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_karting`.`Pilots_has_Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Pilots_has_Results` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Pilots_has_Results` (
  `Pilots_id` INT NOT NULL,
  `Results_id` INT NOT NULL,
  `position` INT NULL,
  `time` TIME NULL,
  PRIMARY KEY (`Pilots_id`, `Results_id`),
  INDEX `fk_Pilots_has_Results_Results1_idx` (`Results_id` ASC) VISIBLE,
  INDEX `fk_Pilots_has_Results_Pilots1_idx` (`Pilots_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pilots_has_Results_Pilots1`
    FOREIGN KEY (`Pilots_id`)
    REFERENCES `Projet_karting`.`Pilots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pilots_has_Results_Results1`
    FOREIGN KEY (`Results_id`)
    REFERENCES `Projet_karting`.`Results` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_karting`.`Races`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Races` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Races` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(45) NOT NULL,
  `date` DATETIME NOT NULL,
  `Type` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_karting`.`pilots_has_races`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`pilots_has_races` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`pilots_has_races` (
  `Pilots_id` INT NOT NULL,
  `Races_id` INT NOT NULL,
  PRIMARY KEY (`Pilots_id`, `Races_id`),
  INDEX `fk_Pilots_has_races_Races1_idx` (`Races_id` ASC) VISIBLE,
  INDEX `fk_Pilots_has_races_Pilots1_idx` (`Pilots_id` ASC) VISIBLE,
  CONSTRAINT `fk_Pilots_has_races_Pilots1`
    FOREIGN KEY (`Pilots_id`)
    REFERENCES `Projet_karting`.`Pilots` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pilots_has_races_Races1`
    FOREIGN KEY (`Races_id`)
    REFERENCES `Projet_karting`.`Races` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Projet_karting`.`Results`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Projet_karting`.`Results` ;

CREATE TABLE IF NOT EXISTS `Projet_karting`.`Results` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME NULL,
  `Races_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_Results_Races1_idx` (`Races_id` ASC) VISIBLE,
  CONSTRAINT `fk_Results_Races1`
    FOREIGN KEY (`Races_id`)
    REFERENCES `Projet_karting`.`Races` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
